<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF7A7PFD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF7A7PFD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF7A7PFD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF7A7PFD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF7A7PFD\App_KernelDevDebugContainer([
    'container.build_hash' => 'F7A7PFD',
    'container.build_id' => '3c440a2f',
    'container.build_time' => 1627302548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF7A7PFD');
